---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-tcp
  namespace: {{ .Release.Namespace }}  
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports: 
  - port: 8080
    targetPort: 8080 
    protocol: TCP
    name: devicecom
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: webapi
  - port: 8880
    targetPort: 8880
    protocol: TCP
    name: httpredirects
  - port: 8843
    targetPort: 8843
    protocol: TCP
    name: httpsredirects
  - port: 6789
    targetPort: 6789
    protocol: TCP
    name: speedtest
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: unifi
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports: 
  - port: 10001
    targetPort: 10001
    protocol: UDP
    name: apdiscovery
  - port: 3478
    targetPort: 3478
    protocol: UDP
    name: stun
  - port: 1900
    targetPort: 1900
    protocol: UDP
    name: appdiscovery    
  - port: 5514
    targetPort: 5514
    protocol: UDP
    name: syslogcapture    
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}

